--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/RxDuZ/AdvancedRewards
build-by-default: true
branches:
- main
projects:
  AdvancedRewards:
    path: ""
    icon: "img/AdvancedRewards.png"
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.5
        branch: pm5
...
