#     ▄████████ ████████▄   ▄█    █▄     ▄████████ ███▄▄▄▄    ▄████████    ▄████████ ████████▄     ▄████████    ▄████████  ▄█     █▄     ▄████████    ▄████████ ████████▄     ▄████████
#    ███    ███ ███   ▀███ ███    ███   ███    ███ ███▀▀▀██▄ ███    ███   ███    ███ ███   ▀███   ███    ███   ███    ███ ███     ███   ███    ███   ███    ███ ███   ▀███   ███    ███
#    ███    ███ ███    ███ ███    ███   ███    ███ ███   ███ ███    █▀    ███    █▀  ███    ███   ███    ███   ███    █▀  ███     ███   ███    ███   ███    ███ ███    ███   ███    █▀
#    ███    ███ ███    ███ ███    ███   ███    ███ ███   ███ ███         ▄███▄▄▄     ███    ███  ▄███▄▄▄▄██▀  ▄███▄▄▄     ███     ███   ███    ███  ▄███▄▄▄▄██▀ ███    ███   ███
#  ▀███████████ ███    ███ ███    ███ ▀███████████ ███   ███ ███        ▀▀███▀▀▀     ███    ███ ▀▀███▀▀▀▀▀   ▀▀███▀▀▀     ███     ███ ▀███████████ ▀▀███▀▀▀▀▀   ███    ███ ▀███████████
#    ███    ███ ███    ███ ███    ███   ███    ███ ███   ███ ███    █▄    ███    █▄  ███    ███ ▀███████████   ███    █▄  ███     ███   ███    ███ ▀███████████ ███    ███          ███
#    ███    ███ ███   ▄███ ███    ███   ███    ███ ███   ███ ███    ███   ███    ███ ███   ▄███   ███    ███   ███    ███ ███ ▄█▄ ███   ███    ███   ███    ███ ███   ▄███    ▄█    ███
#    ███    █▀  ████████▀   ▀██████▀    ███    █▀   ▀█   █▀  ████████▀    ██████████ ████████▀    ███    ███   ██████████  ▀███▀███▀    ███    █▀    ███    ███ ████████▀   ▄████████▀
#                                                                                                 ███    ███                                         ███    ███
# AdvancedRewards made by iRxDuZ

# Do not touch :)
CONFIG_VERSION: 1

# Find sounds here: https://www.digminecraft.com/lists/sound_list_pe.php
# Sound when claiming a reward
reward-claim-sound: "random.levelup"

# Sound when failing to claim a reward
reward-failed-sound: "note.bassattack"

# Broadcast message to claim rewards
# Custom message in /messages.yml
broadcast-claim-rewards: true

# Reward command configuration
command:
  name: "reward"
  description: "Claim your rewards"
  aliases: ["reclaim", "daily"]
